//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaobaoExpress.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long Id { get; set; }
        public string UpdatedEntity { get; set; }
        public string UpdateType { get; set; }
        public string UpdatedValue { get; set; }
        public System.DateTime Created { get; set; }
    }
}
