//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaobaoExpress.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailerProduct
    {
        public long ProductId { get; set; }
        public long RetailerId { get; set; }
        public bool IsManufacturer { get; set; }
        public byte[] ConcurrencyCheck { get; set; }
    
        public virtual Product Products { get; set; }
        public virtual Retailer Retailers { get; set; }
    }
}
